FROM ubuntu:20.04

RUN apt update
RUN apt install -y \
    netcat net-tools iputils-ping curl wget \
    strace ltrace \
    python python3 \
    build-essential \
    screen tmux \
    sudo bash-completion htop \
    nano vim man git