USE $MYSQL_DATABASE;

DROP TABLE IF EXISTS challenge2;
CREATE TABLE challenge2 (
	id INT AUTO_INCREMENT PRIMARY KEY,
	flag VARCHAR(64) NOT NULL
);

DROP USER IF EXISTS '$CHALLENGE2_USER';
CREATE USER '$CHALLENGE2_USER'@'%' IDENTIFIED BY '$CHALLENGE2_USER_PASS';

GRANT USAGE,SELECT ON ${MYSQL_DATABASE}.challenge2 TO ${CHALLENGE2_USER};

INSERT INTO challenge2 (flag) VALUES
	("FLAG-Ash_nazg_durbatuluk_Hl4z");
