USE $MYSQL_DATABASE;

DROP TABLE IF EXISTS challenge3;
CREATE TABLE challenge3 (
	id INT AUTO_INCREMENT PRIMARY KEY,
	flag VARCHAR(128) NOT NULL
);

DROP USER IF EXISTS '$CHALLENGE3_USER';
CREATE USER '$CHALLENGE3_USER'@'%' IDENTIFIED BY '$CHALLENGE3_USER_PASS';

GRANT USAGE,SELECT ON ${MYSQL_DATABASE}.challenge3 TO ${CHALLENGE3_USER};

INSERT INTO challenge3 (flag) VALUES
	("FLAG-In_the_Land_of_Mariadb_where_the_Columns_lie_@>#;rF2T7}8-l3rO");
