version: "3.8"

services:
    # Just build them, the spawner should created them as needed
    unitedctf-sysadmin-base:
        image: unitedctf-sysadmin-base
        build:
            context: ./base
        command: ["/bin/sh", "-c", "echo 'base works' && exit 0"]

    unitedctf-sysadmin-flag0:
        image: unitedctf-sysadmin-flag0
        build:
            context: ./flag0
        command: ["/bin/sh", "-c", "echo 'flag0 works' && exit 0"]
        depends_on:
            - unitedctf-sysadmin-base

    unitedctf-sysadmin-flag1:
        image: unitedctf-sysadmin-flag1
        build:
            context: ./flag1
        command: ["/bin/sh", "-c", "echo 'flag1 works' && exit 0"]
        depends_on:
            - unitedctf-sysadmin-base

    unitedctf-sysadmin-flag2:
        image: unitedctf-sysadmin-flag2
        build:
            context: ./flag2
        command: ["/bin/sh", "-c", "echo 'flag2 works' && exit 0"]
        depends_on:
            - unitedctf-sysadmin-base

    unitedctf-sysadmin-flag3:
        image: unitedctf-sysadmin-flag3
        build:
            context: ./flag3
        command: ["/bin/sh", "-c", "echo 'flag3 works' && exit 0"]
        depends_on:
            - unitedctf-sysadmin-base

    unitedctf-sysadmin-flag4:
        image: unitedctf-sysadmin-flag4
        build:
            context: ./flag4
        command: ["/bin/sh", "-c", "echo 'flag4 works' && exit 0"]
        depends_on:
            - unitedctf-sysadmin-base

    unitedctf-sysadmin-flag5:
        image: unitedctf-sysadmin-flag5
        build:
            context: ./flag5
        command: ["/bin/sh", "-c", "echo 'flag5 works' && exit 0"]
        depends_on:
            - unitedctf-sysadmin-base

    unitedctf-sysadmin-flag6:
        image: unitedctf-sysadmin-flag6
        build:
            context: ./flag6
        command: ["/bin/sh", "-c", "echo 'flag6 works' && exit 0"]
        depends_on:
            - unitedctf-sysadmin-base

    unitedctf-sysadmin-flag7:
        image: unitedctf-sysadmin-flag7
        build:
            context: ./flag7
        command: ["/bin/sh", "-c", "echo 'flag7 works' && exit 0"]
        depends_on:
            - unitedctf-sysadmin-base

    unitedctf-sysadmin-flag8:
        image: unitedctf-sysadmin-flag8
        build:
            context: ./flag8
        command: ["/bin/sh", "-c", "echo 'flag8 works' && exit 0"]
        depends_on:
            - unitedctf-sysadmin-base

    unitedctf-sysadmin-flag9:
        image: unitedctf-sysadmin-flag9
        build:
            context: ./flag9
        command: ["/bin/sh", "-c", "echo 'flag9 works' && exit 0"]
        depends_on:
            - unitedctf-sysadmin-base

    unitedctf-sysadmin-spawner:
        image: unitedctf-sysadmin-spawner
        build:
            context: ./spawner
        hostname: unitedctf-sysadmin-spawner
        restart: unless-stopped
        init: true
        ports:
            - "5022:22"
        volumes:
            # Need to add namespaces
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - unitedctf-sysadmin-base
            - unitedctf-sysadmin-flag1
            - unitedctf-sysadmin-flag2
            - unitedctf-sysadmin-flag3
            - unitedctf-sysadmin-flag4
            - unitedctf-sysadmin-flag5
            - unitedctf-sysadmin-flag6
            - unitedctf-sysadmin-flag7
            - unitedctf-sysadmin-flag8
            - unitedctf-sysadmin-flag9
