version: "3"
services:
    aes-client:
        build: ./crypto/aes-client
        restart: on-failure
        ports:
            - 3000:3000

    aes-ctr:
        build: ./crypto/aes-ctr
        restart: on-failure
        ports:
            - 3001:3000

    aes-ecb-cut-paste:
        build: ./crypto/aes-ecb-cut-paste
        restart: on-failure
        ports:
            - 3002:3000

    le_ruisseau_pwn:
        build: ./pwning/le_ruisseau/
        image: le_ruisseau_pwn
        volumes:
            - ./pwning/le_ruisseau/le_ruisseau:/home/ruisseau/le_ruisseau:ro
            - ./pwning/le_ruisseau/xinetd:/etc/xinetd.d/xinetd:ro
        ports:
            - 17001:8888
        ulimits:
            nprocs: 2048
        restart: unless-stopped
