version: "3"
services:
    aes-client:
        build: ./crypto/aes-client
        restart: on-failure
        ports:
            - 3000:3000

    aes-ctr:
        build: ./crypto/aes-ctr
        restart: on-failure
        ports:
            - 3001:3000

    aes-ecb-cut-paste:
        build: ./crypto/aes-ecb-cut-paste
        restart: on-failure
        ports:
            - 3002:3000

    la_goutte_pwn:
        build: ./pwning/la_goutte
        image: la_goutte_pwn
        volumes:
            - ./pwning/la_goutte/la_goutte:/home/goutte/la_goutte:ro
            - ./pwning/la_goutte/xinetd:/etc/xinetd.d/xinetd:ro
        ports:
            - 17000:8888
        ulimits:
            nproc: 2048
        restart: unless-stopped
