version: "3"
services:
    aes-client:
        build: ./crypto/aes-client
        restart: on-failure
        ports:
            - 3000:3000

    aes-ctr:
        build: ./crypto/aes-ctr
        restart: on-failure
        ports:
            - 3001:3000

    aes-ecb-cut-paste:
        build: ./crypto/aes-ecb-cut-paste
        restart: on-failure
        ports:
            - 3002:3000
