version: "3"
services:
    aes-client:
        build: ./crypto/aes-client
        restart: on-failure
        ports:
            - 3000:3000

    aes-ctr:
        build: ./crypto/aes-ctr
        restart: on-failure
        ports:
            - 3001:3000

    aes-ecb-byte-per-byte:
        build: ./crypto/aes-ecb-byte-per-byte
        restart: on-failure
        ports:
            - 3003:3000

    aes-ecb-cut-paste:
        build: ./crypto/aes-ecb-cut-paste
        restart: on-failure
        ports:
            - 3002:3000
    
    init-socket:
        build: ./programming/init-json
        restart: on-failure
        ports:
            - 3004:3000

    init-json:
        build: ./programming/init-json
        restart: on-failure
        ports:
            - 3005:3000

    la_goutte_pwn:
        build: ./pwning/la_goutte
        image: la_goutte_pwn
        volumes:
            - ./pwning/la_goutte/la_goutte:/home/goutte/la_goutte:ro
            - ./pwning/la_goutte/xinetd:/etc/xinetd.d/xinetd:ro
        ports:
            - 17000:8888
        ulimits:
            nproc: 2048

    le_ruisseau_pwn:
        build: ./pwning/le_ruisseau/
        image: le_ruisseau_pwn
        volumes:
            - ./pwning/le_ruisseau/le_ruisseau:/home/ruisseau/le_ruisseau:ro
            - ./pwning/le_ruisseau/xinetd:/etc/xinetd.d/xinetd:ro
        ports:
            - 17001:8888

    le_lac_pwn:
        build: ./pwning/le_lac
        image: le_lac_pwn
        volumes:
            - ./pwning/le_lac/le_lac:/home/lac/le_lac:ro
            - ./pwning/le_lac/xinetd:/etc/xinetd.d/xinetd:ro
            - ./pwning/le_lac/flag:/flag:ro
        ports:
            - 17002:8888
        ulimits:
            nproc: 2048
        restart: unless-stopped

    sqli_database:
        build:
            context: ./web/sqli/sqli_db/
        env_file:
            - ./web/sqli/sqli_db/.env
            - ./web/sqli/sqli_db/db.env
        restart: unless-stopped
        networks:
            - sqli-net

    sqli_web:
        build: ./web/sqli/sqli_website/
        depends_on:
            - sqli_database
        ports:
            - 18000:80
        volumes:
            - "./web/sqli/sqli_website/src:/var/www/html"
        env_file: ./web/sqli/sqli_db/.env
        environment:
            DB_HOST: sqli_database
        restart: unless-stopped
        networks:
            - sqli-net

networks:
    sqli-net:
